INDICATEUR_LIST = [
    {
        "code": " IND_1",
        "seuil": 0.2,
        "criticite": 5,
        "options": "Indicateur_1",
        "value": "indicateur 1 :calcul de la TVA",
    },
]

INDICATEUR_LIST_DROPDOWN = [
    {"label": "Indicateur 1", "value": "IND_1"},
    {"label": "Indicateur 2", "value": "IND_2"},
    {"label": "Indicateur 3", "value": "IND_3"},
    {"label": "Indicateur 4", "value": "IND_4"},            
    {"label": "Indicateur 5", "value": "IND_5"},
    {"label": "Indicateur 6", "value": "IND_6"},
    {"label": "Indicateur 7", "value": "IND_7"},
    {"label": "Indicateur 8", "value": "IND_8"},
    {"label": "Indicateur 9", "value": "IND_9"},
    {"label": "Indicateur 10", "value": "IND_10"},
    {"label": "Indicateur 11", "value": "IND_11"},
    {"label": "Indicateur 12", "value": "IND_12"},
    {"label": "Indicateur 13", "value": "IND_13"},
    {"label": "Indicateur 14", "value": "IND_14"},
    {"label": "Indicateur 15", "value": "IND_15"},
    {"label": "Indicateur 16", "value": "IND_16"},
    {"label": "Indicateur 17", "value": "IND_17"},
    {"label": "Indicateur 18", "value": "IND_18"},  
    {"label": "Indicateur 19", "value": "IND_19"},
    {"label": "Indicateur 20", "value": "IND_20"},
    {"label": "Indicateur 21", "value": "IND_21"},
    {"label": "Indicateur 22", "value": "IND_22"},
    {"label": "Indicateur 23", "value": "IND_23"},
    {"label": "Indicateur 24", "value": "IND_24"},
    {"label": "Indicateur 25", "value": "IND_25"},
    {"label": "Indicateur 26", "value": "IND_26"},
    {"label": "Indicateur 27", "value": "IND_27"},
    {"label": "Indicateur 28", "value": "IND_28"},
    {"label": "Indicateur 29", "value": "IND_29"},                          
    {"label": "Indicateur 30", "value": "IND_30"},
    {"label": "Indicateur 31", "value": "IND_31"},
    {"label": "Indicateur 32", "value": "IND_32"},
    {"label": "Indicateur 33", "value": "IND_33"},
    {"label": "Indicateur 34", "value": "IND_34"},
    {"label": "Indicateur 35", "value": "IND_35"},
    {"label": "Indicateur 36", "value": "IND_36"},
    {"label": "Indicateur 37", "value": "IND_37"},
    {"label": "Indicateur 38", "value": "IND_38"},
    {"label": "Indicateur 39", "value": "IND_39"},
    {"label": "Indicateur 40", "value": "IND_40"},
    {"label": "Indicateur 41", "value": "IND_41"},
    {"label": "Indicateur 42", "value": "IND_42"},
    {"label": "Indicateur 43", "value": "IND_43"},
    {"label": "Indicateur 44", "value": "IND_44"},
    {"label": "Indicateur 45", "value": "IND_45"},
    {"label": "Indicateur 46", "value": "IND_46"} ]