BASE_COLUMNS = [
    "NUM_IFU",
    "ANNEE",
    "CODE_STRUCTURE",
    "LIBELLE_STRUCTURE",
    "RAISON_SOCIALE",
    "PERIODE_FISCALE",
    "ETAT",
    "REGIME_FISCALE",
    "DATE_DEBUT_ACTIVITE",
    "SECTEUR_ACTIVITE",
    "TYPE_CONTROLE",
    "FORME_JURIDIQUE",
    "HIERARCHIE_2",
    "HIERARCHIE_3",
    "HIERARCHIE_2",
    "HIERARCHIE_3",
    "RISQUE_IND_1",
    "GAP_IND_1",
    "SCORE_IND_1",
    "RISQUE_IND_2",
    "GAP_IND_2",
    "SCORE_IND_2",
    "RISQUE_IND_12",
    "GAP_IND_12",
    "SCORE_IND_12",
    "RISQUE_IND_8",
    "GAP_IND_8",
    "SCORE_IND_8",
    "RISQUE_IND_14",
    "RISQUE_IND_13",
    "GAP_IND_13",
    "SCORE_IND_13",
    "RISQUE_IND_3",
    "AGE_MOIS_IND_3",
    "RISQUE_IND_4",
    "GAP_IND_4",
    "SCORE_IND_4",
    "RISQUE_IND_5",
    "GAP_IND_5",
    "SCORE_IND_5",
    "RISQUE_IND_20",
    "GAP_IND_20",
    "SCORE_IND_20",
    "RISQUE_IND_27",
    "RISQUE_IND_15_A",
    "RISQUE_IND_15_B",
    "RISQUE_IND_16",
    "RISQUE_IND_38",
    "RISQUE_IND_39",
    "RISQUE_IND_46",
    "RISQUE_IND_47",
    "RISQUE_IND_49",
    "RISQUE_IND_57",
    "RISQUE_IND_58",
]

LABEL_COLUMNS = {
    "NUM_IFU": "Numéro IFU",
    "ANNEE": "Année",
    "CODE_STRUCTURE": "Code Structure",
    "LIBELLE_STRUCTURE": "Libellé Structure",
    "RAISON_SOCIALE": "Raison Sociale",
    "PERIODE_FISCALE": "Période Fiscale",
    "ETAT": "État",
    "REGIME_FISCALE": "Régime Fiscal",
    "DATE_DEBUT_ACTIVITE": "Date Début Activité",
    "SECTEUR_ACTIVITE": "Secteur d'Activité",
    "TYPE_CONTROLE": "Type de Contrôle",
    "FORME_JURIDIQUE": "Forme Juridique",
    "HIERARCHIE_2": "Hiérarchie 2",
    "HIERARCHIE_3": "Hiérarchie 3",
    # indicateur 1
    "RISQUE_IND_1": "Indicateur 1",
    "GAP_IND_1": "Écart Indicateur 1",
    "SCORE_IND_1": "Score Indicateur 1",
    # indicateur 2
    "RISQUE_IND_2": "Indicateur 2",
    "GAP_IND_2": "Écart Indicateur 2",
    "SCORE_IND_2": "Score Indicateur 2",
    # indicateur 3
    "RISQUE_IND_3": "Indicateur 3",
    "GAP_IND_3": "Écart Indicateur 3",
    "AGE_MOIS_IND_3": "Âge en Mois Indicateur  3",
    # indicateur 4
    "RISQUE_IND_4": "Indicateur 4",
    "GAP_IND_4": "Écart Indicateur 4",
    "SCORE_IND_4": "Score Indicateur 4",
    # indicateur 5
    "RISQUE_IND_5": "Indicateur 5",
    "GAP_IND_5": "Écart Indicateur 5",
    "SCORE_IND_5": "Score Indicateur 5",
    # indicateur 12
    "RISQUE_IND_12": "Indicateur 12",
    "GAP_IND_12": "Écart Indicateur 12",
    "SCORE_IND_12": "Score Indicateur 12",
    # indicateur 8
    "RISQUE_IND_8": "Indicateur 8",
    "GAP_IND_8": "Écart Indicateur 8",
    "SCORE_IND_8": "Score Indicateur 8",
    # indicateur 13
    "RISQUE_IND_13": "Indicateur 13",
    "GAP_IND_13": "Écart Indicateur 13",
    "SCORE_IND_13": "Score Indicateur 13",
    # indicateur 14
    "RISQUE_IND_14": "Indicateur 14",
    "GAP_IND_14": "Écart Indicateur 14",
    "SCORE_IND_14": "Score Indicateur 14",
    # indicateur 20
    "RISQUE_IND_20": "Indicateur 20",
    "GAP_IND_20": "Écart Indicateur 20",
    "SCORE_IND_20": "Score Indicateur 20",
    # indicateur 27
    "RISQUE_IND_27": "Indicateur 27",
    "RISQUE_IND_15_A": "Indicateur 15A",
    "RISQUE_IND_15_B": "Indicateur 15B",
    "RISQUE_IND_16": "Indicateur 16",
    "RISQUE_IND_38": "Indicateur 38",
    "RISQUE_IND_39": "Indicateur 39",
    "RISQUE_IND_46": "Indicateur 46",
    "RISQUE_IND_47": "Indicateur 47",
    "RISQUE_IND_49": "Indicateur 49",
    "Actions": "Actions",
}

COLS_DAG = [
    {
        "field": "NUM_IFU",
        "headerName": "Numéro IFU",
        "showDefault": True,
        "filter": True,
        "lockPosition": "left",
    },
    {"field": "ANNEE", "headerName": "Année", "filter": True, "showDefault": True},
    {"field": "CODE_STRUCTURE", "headerName": "Code Structure", "showDefault": False},
    {
        "field": "LIBELLE_STRUCTURE",
        "headerName": "Libellé Structure",
        "showDefault": False,
    },
    {"field": "RAISON_SOCIALE", "headerName": "Raison Sociale", "showDefault": False},
    {"field": "PERIODE_FISCALE", "headerName": "Période Fiscale", "showDefault": False},
    {"field": "ETAT", "headerName": "État", "showDefault": False},
    {"field": "REGIME_FISCALE", "headerName": "Régime Fiscal", "showDefault": False},
    {
        "field": "DATE_DEBUT_ACTIVITE",
        "headerName": "Date Début Activité",
        "showDefault": False,
    },
    {
        "field": "SECTEUR_ACTIVITE",
        "headerName": "Secteur d'Activité",
        "showDefault": False,
    },
    {"field": "TYPE_CONTROLE", "headerName": "Type de Contrôle", "showDefault": False},
    {"field": "FORME_JURIDIQUE", "headerName": "Forme Juridique", "showDefault": False},
    {"field": "HIERARCHIE_2", "headerName": "Hiérarchie 2", "showDefault": False},
    {"field": "HIERARCHIE_3", "headerName": "Hiérarchie 3", "showDefault": False},
    # indicateur 1
    {"field": "RISQUE_IND_1", "headerName": "Indicateur 1", "showDefault": False},
    {"field": "GAP_IND_1", "headerName": "Écart Indicateur 1", "showDefault": False},
    {"field": "SCORE_IND_1", "headerName": "Score Indicateur 1", "showDefault": False},
    # indicateur 2
    {"field": "RISQUE_IND_2", "headerName": "Indicateur 2", "showDefault": False},
    {"field": "GAP_IND_2", "headerName": "Écart Indicateur 2", "showDefault": False},
    {"field": "SCORE_IND_2", "headerName": "Score Indicateur 2", "showDefault": False},
    # indicateur 3
    {"field": "RISQUE_IND_3", "headerName": "Indicateur 3", "showDefault": False},
    {"field": "GAP_IND_3", "headerName": "Écart Indicateur 3", "showDefault": False},
    {
        "field": "AGE_MOIS_IND_3",
        "headerName": "Âge en Mois Indicateur  3",
        "showDefault": False,
    },
    # indicateur 4
    {"field": "RISQUE_IND_4", "headerName": "Indicateur 4", "showDefault": False},
    {"field": "GAP_IND_4", "headerName": "Écart Indicateur 4", "showDefault": False},
    {"field": "SCORE_IND_4", "headerName": "Score Indicateur 4", "showDefault": False},
    # indicateur 5
    {"field": "RISQUE_IND_5", "headerName": "Indicateur 5", "showDefault": False},
    {"field": "GAP_IND_5", "headerName": "Écart Indicateur 5", "showDefault": False},
    {"field": "SCORE_IND_5", "headerName": "Score Indicateur 5", "showDefault": False},
    # indicateur 12
    {"field": "RISQUE_IND_12", "headerName": "Indicateur 12", "showDefault": False},
    {"field": "GAP_IND_12", "headerName": "Écart Indicateur 12", "showDefault": False},
    {
        "field": "SCORE_IND_12",
        "headerName": "Score Indicateur 12",
        "showDefault": False,
    },
    # indicateur 8
    {"field": "RISQUE_IND_8", "headerName": "Indicateur 8", "showDefault": False},
    {"field": "GAP_IND_8", "headerName": "Écart Indicateur 8", "showDefault": False},
    {"field": "SCORE_IND_8", "headerName": "Score Indicateur 8", "showDefault": False},
    # indicateur 13
    {"field": "RISQUE_IND_13", "headerName": "Indicateur 13", "showDefault": False},
    {"field": "GAP_IND_13", "headerName": "Écart Indicateur 13", "showDefault": False},
    {
        "field": "SCORE_IND_13",
        "headerName": "Score Indicateur 13",
        "showDefault": False,
    },
    # indicateur 14
    {"field": "RISQUE_IND_14", "headerName": "Indicateur 14", "showDefault": False},
    {"field": "GAP_IND_14", "headerName": "Écart Indicateur 14", "showDefault": False},
    {
        "field": "SCORE_IND_14",
        "headerName": "Score Indicateur 14",
        "showDefault": False,
    },
    # indicateur 20
    {"field": "RISQUE_IND_20", "headerName": "Indicateur 20", "showDefault": False},
    {"field": "GAP_IND_20", "headerName": "Écart Indicateur 20", "showDefault": False},
    {
        "field": "SCORE_IND_20",
        "headerName": "Score Indicateur 20",
        "showDefault": False,
    },
    # indicateur 27
    {"field": "RISQUE_IND_27", "headerName": "Indicateur 27", "showDefault": False},
    {"field": "RISQUE_IND_15_A", "headerName": "Indicateur 15A", "showDefault": False},
    {"field": "RISQUE_IND_15_B", "headerName": "Indicateur 15B", "showDefault": False},
    {"field": "RISQUE_IND_16", "headerName": "Indicateur 16", "showDefault": False},
    {"field": "RISQUE_IND_38", "headerName": "Indicateur 38", "showDefault": False},
    {"field": "RISQUE_IND_39", "headerName": "Indicateur 39", "showDefault": False},
    {"field": "RISQUE_IND_46", "headerName": "Indicateur 46", "showDefault": False},
    {"field": "RISQUE_IND_47", "headerName": "Indicateur 47", "showDefault": False},
    {"field": "RISQUE_IND_49", "headerName": "Indicateur 49", "showDefault": False},
    {
        "field": "Actions",
        "headerName": "Actions",
        "showDefault": True,
        "lockPosition": "right",
        "cellRenderer": "actionsRenderer",
        "cellRendererParams": {
            "actions": [
                {
                    "icon": "fas fa-file-alt",
                    "label": "Générer une fiche individuelle",
                    "callback": "function(params) { generateFiche(params.data.NUM_IFU); }",
                },
                {
                    "icon": "fas fa-eye",
                    "label": "Voir les détails",
                    "callback": "function(params) { alert('Voir détails pour IFU: ' + params.data.NUM_IFU); }",
                }
            ]
        },
    },
]
