
CREATE TABLE t_immobilisation 
   (	
	"ID" NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	"FDP_AcqApCreat" NUMBER(*,0)  DEFAULT 0 NOT NULL, 
	"FDP_VirepostPost" NUMBER(*,0)  DEFAULT 0 NOT NULL, 
	"BLLDS_AcqApCreat" NUMBER(*,0)  DEFAULT 0 NOT NULL, 
	"BLLDS_VirepostPost" NUMBER(*,0)  DEFAULT 0 NOT NULL, 
	"FCDB_AcqApCreat" NUMBER(*,0)  DEFAULT 0 NOT NULL, 
	"FCDB_VirepostPost" NUMBER(*,0)  DEFAULT 0 NOT NULL, 
	"AII_AcqApCreat" NUMBER(*,0)  DEFAULT 0 NOT NULL, 
	"AII_VirepostPost" NUMBER(*,0)  DEFAULT 0 NOT NULL, 
	"THIP_AcqApCreat" NUMBER(*,0)  DEFAULT 0 NOT NULL, 
	"THIP_VirepostPost" NUMBER(*,0)  DEFAULT 0 NOT NULL, 
	"TIP_AcqApCreat" NUMBER(*,0)  DEFAULT 0 NOT NULL, 
	"TIP_VirepostPost" NUMBER(*,0)  DEFAULT 0 NOT NULL, 
	"BHIP_AcqApCreat" NUMBER(*,0)  DEFAULT 0 NOT NULL, 
	"BHIP_VirepostPost" NUMBER(*,0)  DEFAULT 0 NOT NULL, 
	"BIP_AcqApCreat" NUMBER(*,0)  DEFAULT 0 NOT NULL, 
	"BIP_VirepostPost" NUMBER(*,0)  DEFAULT 0 NOT NULL, 
	"AAI_AcqApCreat" NUMBER(*,0)  DEFAULT 0 NOT NULL, 
	"AAI_VirepostPost" NUMBER(*,0)  DEFAULT 0 NOT NULL, 
	"MMAB_AcqApCreat" NUMBER(*,0)  DEFAULT 0 NOT NULL, 
	"MMAB_VirepostPost" NUMBER(*,0)  DEFAULT 0 NOT NULL, 
	"MT_AcqApCreat" NUMBER(*,0)  DEFAULT 0 NOT NULL, 
	"MT_VirepostPost" NUMBER(*,0)  DEFAULT 0 NOT NULL, 
	"Numero_IFU" VARCHAR2(15 BYTE) NOT NULL,
	"ID_INSD" VARCHAR2(50 BYTE) NOT NULL,
	"Annee" NUMBER NOT NULL
   );


CREATE TABLE t_resultat 
   (	
	"ID" NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	"XA_MargCommerc" NUMBER(*,0) DEFAULT 0 NOT NULL, 
	"XB_CA" NUMBER(*,0) DEFAULT 0 NOT NULL,
	"XH_RESULTAT_HAO" NUMBER(*,0) DEFAULT 0 NOT NULL,
	"XG_RESULT_AO" NUMBER(*,0) DEFAULT 0 NOT NULL,
	"XC_VALEUR_AJOUTEE" NUMBER(*,0) DEFAULT 0 NOT NULL,
	"XD_EXCED_BRUT_EXPL" NUMBER(*,0) DEFAULT 0 NOT NULL,
	"RL_DotAmortProviDep" NUMBER(*,0) DEFAULT 0 NOT NULL,
	"XF_RESULT_FIN" NUMBER(*,0) DEFAULT 0 NOT NULL,
	"RO_ValeurCptCessImmob" NUMBER(*,0) DEFAULT 0 NOT NULL,
	"TO_AutresProdHAO" NUMBER(*,0) DEFAULT 0 NOT NULL,
	"RP_AutresChargHAO" NUMBER(*,0) DEFAULT 0 NOT NULL,
	"RK_ChargDePersonnel" NUMBER(*,0) DEFAULT 0 NOT NULL,
	"TM_TransfChargFin" NUMBER(*,0) DEFAULT 0 NOT NULL,
	"XE_RESULT_EXPL" NUMBER(*,0) DEFAULT 0 NOT NULL,
	"Numero_IFU" VARCHAR2(15 BYTE) NOT NULL,
	"ID_INSD" VARCHAR2(50 BYTE) NOT NULL, 
	"Annee" NUMBER NOT NULL
   );

CREATE TABLE t_dettesFiscales 
   (	
	"ID" NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	"EtatTVA_AnneeN" NUMBER(*,0) DEFAULT 0 NOT NULL, 
	"Numero_IFU" VARCHAR2(15 BYTE) NOT NULL, 
	"ID_INSD" VARCHAR2(50 BYTE) NOT NULL,
	"Annee" NUMBER NOT NULL
   );
   

CREATE TABLE t_production 
   (	
	"ID" NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	"TOTAL_PImmobilise" NUMBER(*,0) DEFAULT 0 NOT NULL, 
	"TOTAL_PVendueHorsOHADA" NUMBER(*,0) DEFAULT 0 NOT NULL,
	"TOTAL_PVendueAutrePays" NUMBER(*,0) DEFAULT 0 NOT NULL,
	"TOTAL_PVenduePays" NUMBER(*,0) DEFAULT 0 NOT NULL,
	"ID_TPExercice" NUMBER(*,0) DEFAULT 0 NOT NULL,
	"Numero_IFU" VARCHAR2(15 BYTE) NOT NULL, 
	"ID_INSD" VARCHAR2(50 BYTE) NOT NULL,
	"Annee" NUMBER NOT NULL
   );

CREATE TABLE t_actif
   (	
	"ID" NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	"AZ_TActifImmob_Brut" NUMBER(*,0) DEFAULT 0 NOT NULL,
	"BI_Clients_Net" NUMBER(*,0) DEFAULT 0 NOT NULL,
	"Numero_IFU" VARCHAR2(15 BYTE) NOT NULL,
	"ID_INSD" VARCHAR2(50 BYTE) NOT NULL, 
	"Annee" NUMBER NOT NULL
   );


CREATE TABLE t_passif
   (	
	"ID" NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	"DN_PRCCT_Net" NUMBER(*,0) DEFAULT 0 NOT NULL,
	"CP_TCPReA_Net" NUMBER(*,0) DEFAULT 0 NOT NULL, 
	"DD_TDFReA_Net" NUMBER(*,0) DEFAULT 0 NOT NULL,
	"Numero_IFU" VARCHAR2(15 BYTE) NOT NULL, 
	"ID_INSD" VARCHAR2(50 BYTE) NOT NULL,
	"Annee" NUMBER NOT NULL
   );


CREATE TABLE  t_detteFinanciere
   (	
	"ID" NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	"TPRC_AnneeN" NUMBER(*,0) DEFAULT 0 NOT NULL, 
	"Numero_IFU" VARCHAR2(15 BYTE) NOT NULL, 
	"ID_INSD" VARCHAR2(50 BYTE) NOT NULL,
	"Annee" NUMBER NOT NULL
   );

CREATE TABLE t_synthese
(
    "ID" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "FR_AnneeN" NUMBER(*,0) DEFAULT 0 NOT NULL,
    "Numero_IFU" VARCHAR2(15) NOT NULL,
	"ID_INSD" VARCHAR2(50 BYTE) NOT NULL,
    "Annee" INTEGER NOT NULL
);