
CREATE TABLE "PROG_DCF"."Note3A_ImmobilisationBrute1" 
   (	
	"ID" NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	"FraisDevProsp_AcqApCreat" NUMBER(*,0) NOT NULL ENABLE, 
	"FraisDevProsp_VirepostPost" NUMBER(*,0) NOT NULL ENABLE,
	"BrevLicLogDroiSim_AcqApCreat" NUMBER(*,0) NOT NULL ENABLE,
	"BrevLicLogDroiSim_VirepostPost" NUMBER(*,0) NOT NULL ENABLE,
	"FdsCommDroiB_AcqApCreat" NUMBER(*,0) NOT NULL ENABLE,
	"FdsCommDroiB_VirepostPost" NUMBER(*,0) NOT NULL ENABLE,
	"AutrImmbIncorp_AcqApCreat" NUMBER(*,0) NOT NULL ENABLE,
	"AutrImmbIncorp_VirepostPost" NUMBER(*,0) NOT NULL ENABLE,
	"TerrHorsImmePlac_AcqApCreat" NUMBER(*,0) NOT NULL ENABLE,
	"TerrHorsImmePlac_VirepostPost" NUMBER(*,0) NOT NULL ENABLE,
	"TerrImmePlac_AcqApCreat" NUMBER(*,0) NOT NULL ENABLE,
	"TerrImmePlac_VirepostPost" NUMBER(*,0) NOT NULL ENABLE,
	"BatHorsImmePlac_AcqApCreat" NUMBER(*,0) NOT NULL ENABLE,
	"BatHorsImmePlac_VirepostPost" NUMBER(*,0) NOT NULL ENABLE,
	"BatImmePlac_AcqApCreat" NUMBER(*,0) NOT NULL ENABLE,
	"BatImmePlac_VirepostPost" NUMBER(*,0) NOT NULL ENABLE,
	"amenagAgenInst_AcqApCreat" NUMBER(*,0) NOT NULL ENABLE,
	"amenagAgenInst_VirepostPost" NUMBER(*,0) NOT NULL ENABLE,
	"MatMobActBiol_AcqApCreat" NUMBER(*,0) NOT NULL ENABLE,
	"MatMobActBiol_VirepostPost" NUMBER(*,0) NOT NULL ENABLE,
	"MatTransp_AcqApCreat" NUMBER(*,0) NOT NULL ENABLE,
	"MatTransp_VirepostPost" NUMBER(*,0) NOT NULL ENABLE,
	"Numero_IFU" VARCHAR2(9 BYTE) NOT NULL ENABLE, 
	"Annee" NUMBER NOT NULL ENABLE
   );
   

CREATE TABLE "PROG_DCF"."Comptes_Resultats" 
   (	
	"ID" NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	"XA_MargCommerc_31_12_N_Net" NUMBER(*,0) NOT NULL ENABLE, 
	"XB_CA_31_12_N_Net" NUMBER(*,0) NOT NULL ENABLE,
	"XH_RESULTAT_HAO_31_12_N_Net" NUMBER(*,0) NOT NULL ENABLE,
	"XG_RESULT_AO_31_12_N_Net" NUMBER(*,0) NOT NULL ENABLE,
	"XC_VALEUR_AJOUTEE_31_12_N_Net" NUMBER(*,0) NOT NULL ENABLE,
	"XD_EXCED_BRUT_EXPL_31_12_N_Net" NUMBER(*,0) NOT NULL ENABLE,
	"RL_DotAmortProviDep31_12_N_Net" NUMBER(*,0) NOT NULL ENABLE,
	"XF_RESULT_FIN_31_12_N_Net" NUMBER(*,0) NOT NULL ENABLE,
	"RO_ValeurCptCessImmob_31_12_N_Net" NUMBER(*,0) NOT NULL ENABLE,
	"TO_AutresProdHAO_31_12_N_Net" NUMBER(*,0) NOT NULL ENABLE,
	"RP_AutresChargHAO_31_12_N_Net" NUMBER(*,0) NOT NULL ENABLE,
	"RK_ChargDePersonnel_31_12_N_Net" NUMBER(*,0) NOT NULL ENABLE,
	"TM_TransfChargFin_31_12_N_Net" NUMBER(*,0) NOT NULL ENABLE,
	"XE_RESULT_EXPL_31_12_N_Net" NUMBER(*,0) NOT NULL ENABLE,
	"Numero_IFU" VARCHAR2(9 BYTE) NOT NULL ENABLE, 
	"Annee" NUMBER NOT NULL ENABLE
   );

CREATE TABLE "PROG_DCF"."Note18_DettesFiscalesSociales" 
   (	
	"ID" NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	"EtatTVA_AnneeN" NUMBER(*,0) NOT NULL ENABLE, 
	"Numero_IFU" VARCHAR2(9 BYTE) NOT NULL ENABLE, 
	"Annee" NUMBER NOT NULL ENABLE
   );

CREATE TABLE "PROG_DCF"."Note32_TtlProduction" 
   (	
	"ID" NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	"TOTAL_PdtionImmobilise_Valeur" NUMBER(*,0) NOT NULL ENABLE, 
	"TOTAL_PdtionVendueHorsOHADA_Valeur" NUMBER(*,0) NOT NULL ENABLE,
	"TOTAL_PdtionVendueAutrPays_Valeur" NUMBER(*,0) NOT NULL ENABLE,
	"TOTAL_PdtionVenduePays_Valeur" NUMBER(*,0) NOT NULL ENABLE,
	"ID_TtlProductionExercice" NUMBER(*,0) NOT NULL ENABLE,
	"Numero_IFU" VARCHAR2(9 BYTE) NOT NULL ENABLE, 
	"Annee" NUMBER NOT NULL ENABLE
   );


CREATE TABLE "PROG_DCF"."Bilan_Actif1" 
   (	
	"ID" NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	"AZ_TtlActifImmob_Exer31_12_N_Brut" NUMBER(*,0) NOT NULL ENABLE, 
	"BI_Clients_Exer31_12_N_Net" NUMBER(*,0) NOT NULL ENABLE,
	"Numero_IFU" VARCHAR2(9 BYTE) NOT NULL ENABLE, 
	"Annee" NUMBER NOT NULL ENABLE
   );

CREATE TABLE "PROG_DCF"."Bilan_Passif" 
   (	
	"ID" NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	"DN_ProviRisqChargCourTerm_Exer31_12_N_Net" NUMBER(*,0) NOT NULL ENABLE, 
	"CP_TtlCptauxPropRessAssim_Exer31_12_N_Net" NUMBER(*,0) NOT NULL ENABLE, 
	"DD_TtlDetFinRessAssim_Exer31_12_N_Net" NUMBER(*,0) NOT NULL ENABLE,
	"Numero_IFU" VARCHAR2(9 BYTE) NOT NULL ENABLE, 
	"Annee" NUMBER NOT NULL ENABLE
   );


CREATE TABLE "PROG_DCF"."Note16A_DettesFinRessourcesAssimiles2" 
   (	
	"ID" NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	"TtlProviRisqCharg_AnneeN" NUMBER(*,0) NOT NULL ENABLE, 
	"Numero_IFU" VARCHAR2(9 BYTE) NOT NULL ENABLE, 
	"Annee" NUMBER NOT NULL ENABLE
   );


CREATE TABLE "PROG_DCF"."Note34_FicheSynthesePrincipauxIndicateursFinanciers2" 
   (	
	"ID" NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	"FondsRoulement_AnneeN" NUMBER(*,0) NOT NULL ENABLE, 
	"Numero_IFU" VARCHAR2(9 BYTE) NOT NULL ENABLE, 
	"Annee" NUMBER NOT NULL ENABLE
   );   
   
